# Generated by Django 2.2.14 on 2020-09-02 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20200902_1408'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='first_name',
            new_name='fname',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='last_name',
            new_name='lname',
        ),
    ]
