# Generated by Django 2.2.14 on 2020-09-04 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20200902_1420'),
    ]

    operations = [
        migrations.CreateModel(
            name='applicationmodel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dob', models.DateField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=70)),
                ('name', models.CharField(max_length=70)),
                ('birth_place', models.CharField(max_length=70)),
                ('fname', models.CharField(max_length=70)),
                ('permanent_address', models.TextField()),
                ('postal_paddress', models.TextField()),
                ('phone', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
