# Generated by Django 2.2.14 on 2020-09-04 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_applicationmodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='applicationmodel',
            old_name='postal_paddress',
            new_name='postal_address',
        ),
        migrations.AlterField(
            model_name='applicationmodel',
            name='phone',
            field=models.IntegerField(),
        ),
    ]
