# Generated by Django 2.2.14 on 2020-09-05 04:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_auto_20200904_1552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationmodel',
            name='doa',
            field=models.DateField(default=datetime.date(2020, 9, 5)),
        ),
    ]
