# Generated by Django 2.2.14 on 2020-09-05 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_auto_20200905_1026'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationmodel',
            name='status',
            field=models.CharField(default='Pending', max_length=70),
        ),
    ]
