# Generated by Django 2.2.14 on 2020-09-05 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_applicationmodel_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationmodel',
            name='remark',
            field=models.CharField(default='Application is Still Pending', max_length=255),
        ),
    ]
