# Generated by Django 2.2.14 on 2020-09-05 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_applicationmodel_remark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationmodel',
            name='gender',
            field=models.CharField(max_length=70),
        ),
    ]
