# Generated by Django 2.2.14 on 2020-09-06 05:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_auto_20200905_2305'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationmodel',
            name='applicant_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='applicationmodel',
            name='doa',
            field=models.DateField(default=datetime.date(2020, 9, 6)),
        ),
        migrations.AlterField(
            model_name='applicationmodel',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='Male', max_length=70),
        ),
    ]
